---
- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Set default deny incoming policy
  ufw:
    direction: incoming
    policy: deny

- name: Set default allow outgoing policy
  ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled
