[Definition]
failregex = ^.*Failed \S+ for (?:invalid user )?\S+ from <HOST>(?: port \d+)?
            ^.*Connection closed by (?:invalid|authenticating) user \S+ <HOST>(?: port \d+)?
            ^.*Invalid user \S+ from <HOST>(?: port \d+)?
ignoreregex =
datepattern = TAI64N
              {^LN-BEG}
